apiVersion: v1
kind: Pod
metadata:
  name: ephemeral-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh","-c"]
    args:
      - echo "Message at $(date)" >> /data/message.txt; sleep 3600;
    volumeMounts:
    - name: temp
      mountPath: /data
  volumes:
  - name: temp
    emptyDir: {}